### ISSUE TITLE
Fetch parse relation column type

### ISSUE THREAD

**Issue by nafplann** [Parziphal/parse#14]
Hello again mate...
How can I fetch a parse relation column type or what kind of relation should I use?, for example users column in parse _Role class.

Thank you

**Comment by Parziphal** [comment]
Hello.
You want to get the users from a role? I think you can do `$role->getUsers();`. The class `ParseRole` is a class of the Parse PHP SDK, please read the documentation here: http://docs.parseplatform.org/php/guide/#roles
