### ISSUE TITLE
Eloquent Queries

### ISSUE THREAD

**Issue by jaisonjebin** [Parziphal/parse#16]
![capture](https://user-images.githubusercontent.com/38039448/38249895-d724f622-376a-11e8-9c2a-271ae6c6e49c.PNG)
How to use Laravel Eloquent Queries such as orWhere

**Comment by Parziphal** [comment]
You have to do so the [Parse-way](http://docs.parseplatform.org/php/guide/#compound-queries):

```
$orQuery = Parziphal\Parse\Query::orQueries($queryA, $queryB);
$results = $orQuery->find();
```
