### ISSUE TITLE
Find results using startsWith, endsWith etc

### ISSUE THREAD

**Issue by mauriciotibox** [Parziphal/parse#20]
How can i use where with "LIKE %value%"?

In ParseQuery, i can use startsWith, endsWith, matches...

**Comment by Parziphal** [comment]
You would call those methods as you would with a ParseQuery:

```
$query->startsWith($key, $value);
```

Any method not "recognized" by `Parziphal\Parse\Query` is passed to the `Parse\ParseQuery` object it wraps.

**Comment by nafplann** [comment]
Hey I have created pr for the issue.. is it correct?
https://github.com/Parziphal/parse/pull/21/

**Comment by mauriciotibox** [comment]
Hello, @nafplann i made exactly this. #21 in a fork. You can use.

https://github.com/mauriciotibox/parse/tree/dev-parse
