### ISSUE TITLE
orQueries example

### ISSUE THREAD

**Issue by nafplann** [Parziphal/parse#23]
Hi.. do you have any examples of how to use orQueries?

**Comment by Parziphal** [comment]
Hi, they're called like this (copypasted from [src/Query.php](https://github.com/Parziphal/parse/blob/master/src/Query.php#L50)).
Note that `Query` refers to `Parziphal\Parse\Query`:

> Pass Query, ParseQuery or Closure, as params or in an array. If Closure is passed, a new Query will be passed as parameter. First element must be an instance of Query.

```php
$orQuery = Query::orQueries($query, $parseQuery);
$orQuery = Query::orQueries([$query, $parseQuery]);
$orQuery = Query::orQueries($query, function(Query $query) { $query->where(...); });
```

**Comment by nafplann** [comment]
thank you, i'll try that
