### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by AlexCatch** [Parziphal/parse#6]
I'm having a hard time using authentication.

Using the default authentication scaffolding, the user logs in successfully but when it hits the 'auth' middleware it fails and treats the user like they're not logged in.

**Comment by Parziphal** [comment]
I found the error, I'll push the fix soon.

**Comment by AlexCatch** [comment]
Thanks, I'll test this and confirm it works.
I'm looking forward to contributing to this project.

**Comment by Parziphal** [comment]
By the way, I just noticed you didn't specify what login method you were using. Since you mentioned the auth scaffolding, I assumed you were using username/password combination, and I indeed had a hard time trying to make it work. heh.
