### ISSUE TITLE
How does pagination work with ObjectModel?

### ISSUE THREAD

**Issue by warrenca** [Parziphal/parse#7]
I've got thousands of data and I'm wondering how pagination works? thanks.

**Comment by Parziphal** [comment]
There's no a specialized method for pagination. It's hard with Parse because Parse's `_id` won't work for this, and using `createdAt` may give wrong results.

**Comment by warrenca** [comment]
Thanks for the reply, I actually ended up using [ParseQuery](https://github.com/parse-community/parse-php-sdk/blob/master/src/Parse/ParseQuery.php),  it has `skip` and `take` methods which pretty much can do the job.

**Comment by Parziphal** [comment]
Oh yea, I assumed you knew about them, you can use the same methods with this lib like `Post::where($where)->skip($skip)->limit($limit)->get();`. I thought you were asking for a speciallized pagination functionality.

Nevertheless, take into account that Parse has a limit on skip; you can't skip beyond 10k documents. There's a little more info here: https://github.com/parse-community/Parse-SDK-JS/issues/298
